# Generated by Django 5.2.6 on 2025-11-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Ready To Deleviry', 'Ready To Ship'), ('Shipped', 'Shipped'), ('Delevired', 'Delevired'), ('Canceled', 'Canceled')], default='Not Paid', max_length=20),
        ),
    ]
